n = (input(print('Digite algo: ')))
print('O tipo da variavel é: ',type(n))
print('É numerico?')
print(n.isnumeric())
print("é alpha?")
print(n.isalpha())
print('É alpha numerico?')
print(n.isalnum())
print('Esta tudo em maiusculo?')
print(n.isupper())
print('Esta tudo em minusculo?')
print(n.islower())
print('tem sommente espaços? ')
print(n.isspace())