numero = int(input(print('Digite um numero de ate 4 caracteres')))
n = str(numero)
print('O numero digitado foi:{}'.format(numero))
print('unidade {}'.format(n[3]))
print('Dezena {}'.format(n[2]))
print('Centena {}'.format(n[1]))
print('milhar {}'.format(n[0]))